from abc import ABC, abstractmethod, abstractproperty
from enum import Enum
from lws.lws_utils import ConfigReader, airtime


class DeviceType(Enum):
    END_DEVICE = 1
    BASE_STATION = 2


class PacketStatus(Enum):
    SUCCESS = 1
    LOST = 2
    COLLIDED = 3



class Packet(object):
    def __init__(self, pkt_len, device_id, device_type, packet_type, timestamp, global_config):
        self.device_id = device_id
        self.device_type = device_type
        self.pkt_len = pkt_len
        self.packet_type = packet_type
        self.global_config = global_config
        self.timestamp = timestamp
        self.set_lora_params()
    
    def set_lora_params(self):
        self.sf = self.global_config.nodeSF
        self.cr = self.global_config.nodeCR
        self.bw = self.global_config.nodeBW
        self.tx_pow = self.global_config.pTx

        # self.trans_range = 150
        self.symbol_time = (2.0**self.sf)/self.bw
        # self.arrive_time = 0
        self.airtime = airtime(self.sf, self.cr, self.pkt_len, self.bw)

    def __repr__(self):
        return "{} packet generated by {}[{}] with a length of {} bytes".format(self.packet_type, self.device_type, self.device_id, self.pkt_len)


class LWSDevice(ABC):

    def __init__(self, device_id, x, y, dist, global_config):
        super().__init__()

        self.device_id = device_id
        self._x = x 
        self._y = y
        self.global_config = global_config
        self.dist = dist

        self.init_params()

        self._num_pkt_sent = 0 
        self._num_pkt_received = 0

        self._pkt_loss_count = 0
        self._pkt_collision_count = 0
        
        self.event_list = []
        
    def add_event(self, timestamp, event):
        self.event_list.append({
            "timestamp" : timestamp,
            "event"     : event
        })

    def init_params(self):
        #TODO: change the global_config attributes to better names e.g. device_sf
        self.sf = self.global_config.nodeSF
        self.cr = self.global_config.nodeCR 
        self.bw = self.global_config.nodeBW
        self.txPow = self.global_config.pTx

    @abstractmethod
    def send_packet(self, packet, target_device):
        pass 
    
    @abstractmethod
    def receive_packet(self, packet, from_device, status, timestamp):
        pass

    def make_packet(self, packet_type, length, timestamp):

        packet = Packet(pkt_len=length, device_id=self.device_id,device_type=self.device_type, packet_type=packet_type, timestamp=timestamp, global_config=self.global_config)
        return packet

    @property
    def num_pkt_sent(self):
        return self.num_pkt_sent

    @property
    def pkt_collision_count(self):
        return self.pkt_collision_count
    
    @property
    def pkt_loss_count(self):
        return self.pkt_loss_count
        
    @abstractproperty
    def device_type(self):
        raise NotImplementedError


class EndDevice(LWSDevice):

    device_type = DeviceType.END_DEVICE

    def __init__(self, device_id, x, y, dist, global_config):
        super().__init__(device_id, x, y, dist, global_config)
        self.retransmission_cnt = 0
        

    def send_packet(self, target_device, timestamp):
        # print("Sent packet {} to target_device {}".format(packet, target_device))
        #generate a packet to send and return the packet
        #packet = device.send_packet(target_device, timestamp)
        #target_device.received_packet(packet, ...)
        self._num_pkt_sent += 1 
    
    def receive_packet(self, packet, from_device, status, timestamp):
        
        if status == PacketStatus.SUCCESS:
            event_str = "Packet {} received from {}.".format(packet, from_device)
            self._num_pkt_received += 1
        elif status == PacketStatus.LOST:
            event_str = "Packet {} from {} is lost.".format(packet, from_device)
            self._pkt_loss_count += 1
        elif status == PacketStatus.COLLIDED:
            event_str = "Packet {} from {} collided.".format(packet,from_device)
            self._pkt_collision_count += 1


        self.add_event(timestamp, event_str)


    def schedule_retransmission(self):
        pass



class BaseStation(LWSDevice):

    device_type = DeviceType.BASE_STATION

    def send_packet(self, packet, target_device):
        pass

    def receive_packet(self, packet, from_device, status, timestamp):
        pass
    


if __name__ == "__main__":
    config = ConfigReader("./lora_sim_config.json")
    end_device = EndDevice(0,1,2,3, config)
    print(end_device.sf, end_device.device_type)
